# Generated by Django 5.0.7 on 2024-07-31 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper_start_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_time', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.student')),
            ],
        ),
    ]
