# Generated by Django 5.0.7 on 2024-08-01 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0004_paper_finish_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_of_student', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.questions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.student')),
            ],
        ),
    ]
