# Generated by Django 5.0.7 on 2024-08-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0008_alter_questions_actual_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
            ],
        ),
    ]
